version: 2
jobs:
  tox-tests:
    docker:
      - image: painless/tox
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: run build and tox
          command: |
            python3 -m venv .env
            . .env/bin/activate
            pip install virtualenv tox
            tox

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  build-container:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
          docker_layer_caching: false # requires upgraded plan
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: build container
          command: |
            docker build -t quay.io/dontlaugh/flask-on-k8s:${CIRCLE_SHA1} .


workflows:
  version: 2
  commit:
    jobs:
      - tox-tests
      - build-container:
          requires:
            - tox-tests
#
#  master-pr:
#    jobs: